### ISSUE TITLE
Version.is_devrelease used but no packaging requirement

### ISSUE THREAD

**Issue by effigies** [astropy/pytest-doctestplus#149]
The latest release uses [`Version.is_devrelease`](https://packaging.pypa.io/en/latest/version.html#packaging.version.Version.is_devrelease), which was [added in packaging 17.0](https://packaging.pypa.io/en/latest/changelog.html#id15).

Here's the truncated traceback if you have an older packaging installed.

```Python
  File ".../virtenv/lib/python3.6/site-packages/pytest_doctestplus/plugin.py", line 25, in <module>
    PYTEST_GE_6_3 = _pytest_version.is_devrelease or _pytest_version >= Version('6.3')
AttributeError: 'Version' object has no attribute 'is_devrelease'
```

The fix is obviously to upgrade packaging, but it would be nice to let pip resolve it.

**Comment by pllim** [comment]
Thanks for reporting this! Yeah, I think we could specify a minversion here:

https://github.com/astropy/pytest-doctestplus/blob/515b68964a6007386c4d1020d51210e92f0d660b/setup.cfg#L33

We never specified it as a requirement because `pytest` requires it but nothing stops us from doing so from now on. What do you think, @saimn ?

**Comment by saimn** [comment]
Yes, seems fine to add this requirement.

**Comment by effigies** [comment]
Thanks for the quick response. I'll submit a PR momentarily.
