### ISSUE TITLE
Add more extended testing with downstream packages

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-doctestplus#77]
Given that the primary audience for this plugin was astropy, I feel it would be extremely  useful to have a testing job  that actually  run the astropy tests to make sure we don't break compatibility here.

**Comment by vanyakosmos** [comment]
what do you mean by "run astropy tests"? Do you want to make separate workflow in CI? Something like this:
- setup python
- git ccheckout doctestplus
- install it locally with `pip install -e`
- git checkout latest astropy
- install dependencies (doctestplus from pypi will be ignored because package with the same name is already installed)
- run tests

**Comment by bsipocz** [comment]
Yes, the gist is something like that. I opened this issue mostly as a reminder and as a place for discussion in case @astrofrog has opinions whether we can or rather shouldn't do this.

**Comment by bsipocz** [comment]
This in fact went the other way and downstream is now cron testing with the dev version of the infrastructure packages, so I'm closing this issue now.
